#!/usr/bin/env bash
# Bash script to ping the given IP Address after checking if it was passed
numArgs="$#"

if (( numArgs < 1 ))
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
