#!/usr/bin/env bash
# Bash script to configure the hosts file used to resolve domain names

cp /etc/hosts ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
echo "127.0.0.2	localhost" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
